---
apiVersion: traefik.io/v1
kind: IngressRouteTCP
metadata:
  name: arc-sshd-ingressroute
spec:
  entryPoints:
    - tcp-ingress
  routes:
  - match: HostSNI(`*`)
    services:
    - name: arc-sshd-svc
      port: 64022

