apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.priority: "44"
spec:
  rules:
  - host: {{ .Values.deployment.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor
            port:
              number: 80
