apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pvc
  namespace: {{ index .Values "skaha-workload" "namespace" }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{- if not (eq .Values.storage.skaha.claim.storageClassName nil) }}
  storageClassName: {{ .Values.storage.skaha.claim.storageClassName }}
  {{- end }}
  selector:
    matchLabels:
{{- toYaml .Values.storage.skaha.claim.labels | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.skaha.namespace }}-cavern-pvc
  namespace: {{ .Values.skaha.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{- if .Values.storage.sessions.claim.storageClassName }}
  storageClassName: {{ .Values.storage.sessions.claim.storageClassName }}
  {{- end }}
  selector:
    matchLabels:
{{- toYaml .Values.storage.sessions.claim.labels | nindent 6 }}
