apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pvc
  namespace: {{ index .Values "skaha-workload" "namespace" }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{- if not (eq .Values.storage.sessions.claim.storageClassName nil) }}
  storageClassName: {{ .Values.storage.sessions.claim.storageClassName }}
  {{- end }}
  selector:
    matchLabels:
{{- toYaml .Values.storage.sessions.claim.labels | nindent 6 }}
