apiVersion: v1
kind: Service
metadata:
  name: skaha-tomcat-svc
  labels:
    run: skaha-tomcat-svc
spec:
  ports: {{ toYaml .Values.service.skaha_tomcat_svc.ports | nindent 2 }}
  selector:
    run: skaha-tomcat
