apiVersion: batch/v1
kind: Job
metadata:
  name: "skaha-add-project"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "skaha-add-project"
        image: images.canfar.net/skaha-system/add-project:1.0
        imagePullPolicy: IfNotPresent
        # TODO: automate the setting of this in the calling script
        command: ["/usr/bin/add-project"]
        # args: project-dir-name, owner-userid, project-group-name, read-only or read-write
        args: ["myproject", "majorb", "mygroup", "read-write"]
        volumeMounts:
        - mountPath: "/config"
          name: add-project-config
        - mountPath: "/arc"
          name: cavern-volume
          subPath: cavern
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      securityContext:
        runAsUser: 0
      serviceAccountName: skaha
      volumes:
      - name: add-user-config
        configMap:
          name: add-user-config
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
