apiVersion: v1
kind: Service
metadata:
  name: arcade-tomcat-svc
  labels:
    run: arcade-tomcat-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http-connection
  selector:
    run: arcade-tomcat
