apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cavern-tomcat
  name: cavern-tomcat
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cavern-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cavern-tomcat
    spec:
      containers:
      - name: cavern-tomcat
        image: canfar-registry.cloud.computecanada.ca/cavern-tomcat:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.ssl/
          name: servops-cert
          readOnly: true
        - mountPath: "/cephfs"
          name: cavern-ceph-volume
        - mountPath: "/config"
          name: config-volume
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: cavern-servops-secret
      - name: cavern-ceph-volume
        persistentVolumeClaim:
          claimName: cavern-ceph-claim-20200608
      - name: config-volume
        configMap:
          name: cavern-config
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
