apiVersion: v1
kind: ConfigMap
metadata:
  name: posix-mapper-config
  namespace: {{ .Values.skaha.namespace }}
data:
  cadc-registry.properties: |+
    #
    # local authority map
    #
    # <base standardID> = <authority>
  
    ivo://ivoa.net/std/GMS#search-1.0 = ivo://skao.int/gms
    ivo://ivoa.net/sso#OAuth = https://ska-iam.stfc.ac.uk/
    ivo://ivoa.net/sso#OpenID = https://ska-iam.stfc.ac.uk/
  
    http://www.opencadc.org/std/posix#group-mapping-0.1 = {{ .Values.deployment.posixMapper.resourceID }}
    http://www.opencadc.org/std/posix#user-mapping-0.1 = {{ .Values.deployment.posixMapper.resourceID }}
  
    ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ .Values.deployment.posixMapper.registryURL }}
  
  catalina.properties: |-
    tomcat.connector.scheme=https
    tomcat.connector.proxyName={{ .Values.deployment.hostname }}
    tomcat.connector.proxyPort=443
    ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
    ca.nrc.cadc.util.Log4jInit.messageOnly=true
    # (default: ca.nrc.cadc.auth.NoOpIdentityManager)
    ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager
  
    org.opencadc.posix.mapper.maxActive=4
    org.opencadc.posix.mapper.username={{ .Values.postgresql.auth.username }}
    org.opencadc.posix.mapper.password={{ .Values.postgresql.auth.password }}
    org.opencadc.posix.mapper.url=jdbc:postgresql://posix-mapper-postgres.{{ .Values.skaha.namespace }}.svc.{{ .Values.kubernetesClusterDomain }}:5432/{{ .Values.postgresql.auth.database }}
  posix-mapper.properties: |
    # service identity
    org.opencadc.posix.mapper.resourceID={{ .Values.deployment.posixMapper.resourceID }}
  
    # database schema
    org.opencadc.posix.mapper.schema={{ .Values.postgresql.auth.schema }}
  
    # ID ranges to allow some customization where administration is necessary
    org.opencadc.posix.mapper.uid.start={{ .Values.deployment.posixMapper.minUID }}
    org.opencadc.posix.mapper.gid.start={{ .Values.deployment.posixMapper.minGID }}
