---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: 1209600
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: Never
      ${skaha.schedulegpu}
      imagePullSecrets:
      - name: ${software.imagesecret}
      hostname: "${software.hostname}"
      securityContext:
        runAsUser: ${skaha.posixid}
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
      initContainers:
      - name: setup-access-token
        image: busybox
        command: ["sh", "-c", "echo '${skaha.accesstoken}' > ${skaha.accesstoken.path}/${skaha.accesstoken.file}"]
        volumeMounts:
        - name: token-dir
          mountPath: ${skaha.accesstoken.path}
      containers:
      - name: "${skaha.jobname}"
        ${headless.image.bundle}
        securityContext:
          runAsUser: ${skaha.posixid}
          runAsGroup: ${skaha.posixid}
          allowPrivilegeEscalation: false
        workingDir: "/arc/home/${skaha.userid}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
            ephemeral-storage: "5Gi"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
            nvidia.com/gpu: "${software.limits.gpus}"
            ephemeral-storage: "5Gi"
        volumeMounts:
        - mountPath: "${skaha.accesstoken.path}"
          name: token-dir
          readOnly: true
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
      volumes:
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: token-dir
        emptyDir: {}
