---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: ${skaha.sessionexpiry}
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: OnFailure
      ${skaha.schedulegpu}
      imagePullSecrets:
      - name: ${software.imagesecret}
      securityContext:
        runAsUser: ${skaha.posixid}
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
      priorityClassName: uber-user-preempt-medium
      hostname: "${software.hostname}"
      initContainers:
      - name: setup-access-token
        image: busybox
        command: ["sh", "-c", "echo '${skaha.accesstoken}' > ${skaha.accesstoken.path}/${skaha.accesstoken.file}"]
        volumeMounts:
        - name: token-dir
          mountPath: ${skaha.accesstoken.path}
      containers:
      - name: "${skaha.jobname}"
        command: ["/skaha-system/start-desktop.sh"]
        args:
        - "${skaha.hostname}"
        env:
        - name: HOME
          value: "/arc/home/${skaha.userid}"
        - name: VNC_PW
          value: "${skaha.sessionid}"
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        - name: MOZ_FORCE_DISABLE_E10S
          value: "1"
        securityContext:
          runAsUser: ${skaha.posixid} 
          runAsGroup: ${skaha.posixid}
        image: ${software.imageid}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "500Mi"
            cpu: "250m"
            ephemeral-storage: "5Gi"
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "${skaha.accesstoken.path}"
          name: token-dir
          readOnly: true
        - mountPath: "/desktopstartup"
          name: templates
        - mountPath: "/skaha-system"
          name: start-desktop
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
      volumes:
      - name: templates
        configMap:
          name: templates
          defaultMode: 0777
      - name: start-desktop
        configMap:
          name: start-desktop
          defaultMode: 0777
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: token-dir
        emptyDir: {}
