namespace: skaha-system
resources:
- skaha-tomcat-deployment.yaml
- skaha-tomcat-expose.yaml
- skaha-wsproxy-deployment.yaml
- skaha-wsproxy-expose.yaml
- carta-ingress.yaml
- desktop-ingress.yaml
- notebook-ingress.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: skaha-config
  files:
  - config/catalina.properties
  - config/LocalAuthority.properties
  - config/launch-carta.yaml
  - config/launch-notebook.yaml
  - config/launch-novnc.yaml
  - config/launch-software.yaml
  - config/skaha-software.properties
  - config/k8s-resources.properties
- name: skaha-wsproxy-config
  files:
  - config/k8s-config
generatorOptions:
 disableNameSuffixHash: true
