apiVersion: v1
kind: Service
metadata:
  name: skaha-wsproxy-svc
  labels:
    run: skaha-wsproxy-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http-connection
  selector:
    run: skaha-wsproxy
