apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ac-tomcat
  name: ac-tomcat
  namespace: skaha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ac-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ac-tomcat
    spec:
      containers:
      - name: ac-tomcat
        image: canfar-registry.cloud.computecanada.ca/ac:0.1
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 8675309
          runAsGroup: 8675309
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "4Gi"
            cpu: "0.5"
          limits:
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /usr/share/tomcat/.ssl/
          name: servops-cert
        - mountPath: /usr/share/tomcat/
          name: db-config
        - mountPath: "/usr/share/tomcat/config"
          name: config-volume
      #  - mountPath: "/config"
      #    name: tomcat-config-volume
      volumes:
      - name: servops-cert
        secret:
          defaultMode: 420
          secretName: cavern-servops-secret
      - name: config-volume
        configMap:
          name: ac-config
          defaultMode: 420
#      - name: tomcat-config-volume
#        configMap:
#          name: ac-tomcat-config
      - name: db-config
        secret:
          defaultMode: 420
          secretName: ac-dbrc
