apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: skaha-contributed-middleware-${skaha.sessionid}
spec:
  replacePathRegex:
    regex: ^/session/contributed/${skaha.sessionid}(/|$)(.*)
    replacement: /$2

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: skaha-contributed-ingress-${skaha.sessionid}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`ws-uv.canfar.net`) && PathPrefix(`/session/contributed/${skaha.sessionid}/`)
    services:
    - kind: Service
      name: skaha-contributed-svc-${skaha.sessionid}
      port: 5000
      scheme: http
    middlewares:
      - name: skaha-contributed-middleware-${skaha.sessionid}
