apiVersion: v1
kind: Service
metadata:
  name: arcade-wsproxy-svc
  labels:
    run: arcade-wsproxy-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http-connection
  selector:
    run: arcade-wsproxy
