---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: 259200
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      imagePullSecrets:
      - name: ${software.imagesecret}
      securityContext:
        runAsUser: ${skaha.posixid}
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
      containers:
      - name: "${skaha.jobname}"
        env:
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        securityContext:
          runAsUser: ${skaha.posixid} 
          runAsGroup: ${skaha.posixid}
        image: ${software.imageid}
        command: ["/bin/sh", "-c"]
        args:
        - /carta/arcade-carta /arc /arc/projects
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
        ports:
        - containerPort: 5901
          protocol: TCP
          name: websocket-port
        - containerPort: 6901
          protocol: TCP
          name: frontend-port
        volumeMounts:
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
