---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  activeDeadlineSeconds: 1209600
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: OnFailure
      ${skaha.schedulegpu}
      imagePullSecrets:
        - name: "${software.imagesecret}"
      securityContext:
        runAsUser: ${skaha.posixid} 
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [100, ${skaha.supgroups}]
      priorityClassName: uber-user-preempt-medium
      initContainers:
      - name: init-python-dir
        image: busybox
        securityContext:
          runAsUser: ${skaha.posixid}
          runAsGroup: ${skaha.posixid}
        command: ["mkdir", "-p", "/arc/home/${skaha.userid}/.local/lib/python3.8/site-packages"]
        #args:
        #- mkdir -p /arc/home/${skaha.userid}/.local/lib/python3.7/site-packages
        volumeMounts:
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
#      - name: init-lab
#        image: ${software.imageid}
#        securityContext:
#          runAsUser: ${skaha.posixid}
#          runAsGroup: ${skaha.posixid}
#        command: ["/opt/conda/bin/jupyter", "lab", "build"]
#        env:
#        - name: JUPYTER_TOKEN
#          value: "${skaha.sessionid}"
#        - name: JUPYTER_CONFIG_DIR
#          value: "/arc/home/${skaha.userid}"
#        - name: JUPYTER_PATH
#          value: "/arc/home/${skaha.userid}"
#        - name: JUPYTERLAB_DIR
#          value: "/arc/home/${skaha.userid}/skaha-lab"
#        - name: NB_USER
#          value: "${skaha.userid}"
#        - name: NB_UID
#          value: "${skaha.posixid}"
#        - name: HOME
#          value: "/arc/home/${skaha.userid}"
#        - name: PWD
#          value: "/arc/home/${skaha.userid}"
#        - name: XDG_CACHE_HOME
#          value: "/arc/home/${skaha.userid}"
#        volumeMounts:
#        - mountPath: "/arc"
#          name: cavern-volume
#          subPath: "cavern"
#        - mountPath: /var/lib/sss/pipes
#          name: sssd-dir
#          readOnly: true
      containers:
      - name: "${skaha.jobname}"
        env:
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        - name: JUPYTER_TOKEN
          value: "${skaha.sessionid}"
        - name: JUPYTER_CONFIG_DIR
          value: "/arc/home/${skaha.userid}"
        - name: JUPYTER_PATH
          value: "/arc/home/${skaha.userid}"
#        - name: JUPYTERLAB_DIR
#          value: "/arc/home/${skaha.userid}/skaha-lab"
        - name: NB_USER
          value: "${skaha.userid}"
        - name: NB_UID
          value: "${skaha.posixid}"
        - name: HOME
          value: "/arc/home/${skaha.userid}"
        - name: PWD
          value: "/arc/home/${skaha.userid}"
        - name: XDG_CACHE_HOME
          value: "/arc/home/${skaha.userid}"
        image: ${software.imageid}
        command: ["start-notebook.sh"]
        args:
          - --NotebookApp.base_url=notebook/${skaha.sessionid}
          - --NotebookApp.notebook_dir=/arc/home/${skaha.userid} 
#          - --NotebookApp.notebook_dir=/arc
          - --NotebookApp.allow_origin="*"
# The following needs to be a 'list'
#          - --NotebookApp.extra_nbextensions_path=/home/jovyan:/arc/home/${skaha.userid}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
            ephemeral-storage: "20Gi"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
            nvidia.com/gpu: "${software.limits.gpus}"
            ephemeral-storage: "200Gi"
        ports:
        - containerPort: 8888
          protocol: TCP
          name: notebook-port
        volumeMounts:
        - mountPath: "/arc"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
