---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      imagePullSecrets:
        - name: "${software.imagesecret}"
      securityContext:
        runAsUser: ${skaha.posixid} 
#        runAsGroup: 100
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
      initContainers:
      - name: init-python-dir
        image: busybox
        securityContext:
          runAsUser: ${skaha.posixid}
          runAsGroup: ${skaha.posixid}
        command: ["mkdir", "-p", "/cavern/home/${skaha.userid}/.local/lib/python3.8/site-packages"]
        #args:
        #- mkdir -p /cavern/home/${skaha.userid}/.local/lib/python3.7/site-packages
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      containers:
      - name: "${skaha.jobname}"
        env:
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        - name: JUPYTER_TOKEN
          value: "${skaha.sessionid}"
        - name: JUPYTER_CONFIG_DIR
          value: "/cavern/home/${skaha.userid}"
        - name: JUPYTER_PATH
          value: "/cavern/home/${skaha.userid}"
        - name: NB_USER
          value: "${skaha.userid}"
        - name: NB_UID
          value: "${skaha.posixid}"
        - name: HOME
          value: "/cavern/home/${skaha.userid}"
        - name: PWD
          value: "/cavern/home/${skaha.userid}"
        - name: XDG_CACHE_HOME
          value: "/cavern/home/${skaha.userid}"
        image: ${software.imageid}
        command: ["start-notebook.sh"]
        args:
          - --NotebookApp.base_url=notebook/${skaha.sessionid}
          - --NotebookApp.notebook_dir=/cavern/home/${skaha.userid} 
          - --NotebookApp.allow_origin="*"
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        resources:
          requests:
            memory: "4Gi"
            cpu: "0.25"
          limits:
            memory: "256Gi"
            cpu: "16"
        ports:
        - containerPort: 8888
          protocol: TCP
          name: notebook-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: kanfarnetes_dev
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
