---
apiVersion: batch/v1
kind: Job
metadata:
  name: "sss-test-2"
#  annotations:
#    seccomp.security.alpha.kubernetes.io/pod: unconfined
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      securityContext:
        runAsUser: 20001
        runAsGroup: 20001
        fsGroup: 20001
        supplementalGroups:
        - 20001
        - 20002
      restartPolicy: OnFailure
      #restartPolicy: Never
      containers:
      - name: "test-job"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: GDK_SYNCHRONIZE
          value: "1"
        - name: SHELL
          value: "/bin/bash"
        securityContext:
          runAsUser: 20001
          runAsGroup: 20001
          allowPrivilegeEscalation: false
#          capabilities:
#            add: ["SETGID"]
        image: canfar-registry.cloud.computecanada.ca/arcade-terminal:latest
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4Gi"
            cpu: "0.25"
          limits:
            memory: "256Gi"
            cpu: "16"
        ports:
        - containerPort: 6000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
