---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
    canfar-net-cores: "${software.cores}"
    canfar-net-ram: "${software.ram}"
  name: "${skaha.jobname}"
spec:
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      restartPolicy: OnFailure
      #restartPolicy: Never
      imagePullSecrets:
      - name: ${software.imagesecret}
      containers:
      - name: "${skaha.jobname}"
        env:
        - name: HOME
          value: "/cavern/home/${skaha.userid}"
        - name: VNC_PW
          value: "${skaha.sessionid}"
        - name: skaha_hostname
          value: "${skaha.hostname}"
        - name: skaha_username
          value: "${skaha.userid}"
        - name: MOZ_FORCE_DISABLE_E10S
          value: "1"
        securityContext:
          runAsUser: ${skaha.posixid} 
          runAsGroup: ${skaha.posixid}
        image: ${software.imageid}
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        #imagePullPolicy: Never
        resources:
          requests:
            memory: "${software.requests.ram}"
            cpu: "${software.requests.cores}"
          limits:
            memory: "${software.limits.ram}"
            cpu: "${software.limits.cores}"
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
          readOnly: true
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/054e398e-a08e-425e-9f7c-fc394362e38e
          user: keel_prod
          secretRef:
            name: cephfs-cephx-key
          readOnly: false          
      - name: scratch-dir
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
