kubernetesClusterDomain: cluster.local
skaha:
  namespace: skaha-system
skaha-workload:
  namespace: skaha-workload

# Set these labels appropriately
storage:
  skaha:
    claim:
      labels:
        storage: my-great-storage
  sessions:
    claim:
      labels:
        storage: my-great-storage

secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted to use client certificates.
  # cacert-secret:
  #   ca.crt: <base64 encoded CA crt>
  # default-certificate:  # Match the default-certificate name in traefik.tlsStore.default.defaultCertificate.secretName
  # For server domains with self-signed certificates, add the Base64 encoded file content here.
    # tls.crt: <base64 encoded server cert>
    # tls.key: <base64 encoded server key>

# Comment the traefik block out if Traefik is already installed
traefik:
  # install: true
  # experimental:
  #   plugins:
  #     enabled: true
  # additionalArguments:
  #   - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
  #   - "--experimental.plugins.htransformation.version=v0.2.7"
  # tlsStore:
  #   default:
  #     defaultCertificate:
  #       # See default-certificate secret(s) above
  #       secretName: default-certificate
  # tlsOptions:
  #   traefik-client-cert-option:
  #     clientAuth:
  #       clientAuthType: VerifyClientCertIfGiven
  #       secretNames:
  #         - cacert-secret
  # websecure:
  #   middlewares: 
  #     - default-traefik-passtlsclientcert@kubernetescrd
  #     - default-traefik-header-transform@kubernetescrd
  #   tls:
  #     options:
  #       - default-traefik-client-cert-option@kubernetescrd
