kubernetesClusterDomain: cluster.local
nfsServer:
  namespace: skaha-nfs
  nfsServer:
    image:
      repository: registry.k8s.io/volume-nfs
      tag: "0.8"
    resources:
      limits:
        cpu: 500m
        memory: 500M
      requests:
        cpu: 250m
        memory: 250M
    ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 0
    - name: mountd
      port: 20048
      targetPort: 0
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: 0
  replicas: 1
  type: ClusterIP
skaha:
  namespace: skaha-system
skaha-workload:
  namespace: skaha-workload

secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted to use client certificates.
  # cacert-secret:
  #   ca.crt: <base64 encoded CA crt>
  # default-certificate:
    # Uncomment to enable server certificates that match your domain.
    # tls.crt: <base64 encoded server certificate>
    # tls.key: <base64 encoded server certificate key>

traefik:
  # experimental:
  #   plugins:
  #     enabled: true
  # additionalArguments:
  #   - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
  #   - "--experimental.plugins.htransformation.version=v0.2.7"
  # tlsStore:
  #   default:
  #     defaultCertificate:
  #       # See default-certificate secret(s) above
  #       secretName: default-certificate
  # tlsOptions:
  #   traefik-client-cert-option:
  #     clientAuth:
  #       clientAuthType: VerifyClientCertIfGiven
  #       secretNames:
  #         - cacert-secret
  # websecure:
  #   middlewares: 
  #     - default-traefik-passtlsclientcert@kubernetescrd
  #     - default-traefik-header-transform@kubernetescrd
  #   tls:
  #     options:
  #       - default-traefik-client-cert-option@kubernetescrd
