kubernetesClusterDomain: cluster.local
nfsServer:
  namespace: skaha-nfs
  nfsServer:
    image:
      repository: registry.k8s.io/volume-nfs
      tag: "0.8"
    resources:
      limits:
        cpu: 500m
        memory: 500M
      requests:
        cpu: 250m
        memory: 250M
    ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 0
    - name: mountd
      port: 20048
      targetPort: 0
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: 0
  replicas: 1
  type: ClusterIP
skaha:
  namespace: skaha-system
skaha-workload:
  namespace: skaha-workload

# traefik:
#   experimental:
#     plugins:
#       enabled: true
#   additionalArguments:
#     - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
#     - "--experimental.plugins.htransformation.version=v0.2.7"
