kubernetesClusterDomain: cluster.local
skaha:
  namespace: skaha-system
skahaWorkload:
  namespace: skaha-workload
  
# Underlying storage creation.  You may not be privileged enough to create PersistentVolumes, so this is
# configurable here.  When installing on a laptop, for example, these will likely be set to true.
# Default is false.
storage:
  # Whether to create the PersistentVolume that will provide a PersistentVolumeClaim to the Skaha service.
  service:
    create: false
    claimName: skaha-pvc
    labels:
      storage: skaha-storage # Labels are VERY relevant.  They should match the values.yaml configuration.  Match this up with the PersistentVolumeClaim when installing Skaha.

  # Whether to create the PersistentVolume that will provide a PersistentVolumeClaim to the User Sesisons.
  session:
    create: false
    storage: local-storage

secrets:
  # default-certificate:  # Match the default-certificate name in traefik.tlsStore.default.defaultCertificate.secretName
  # For server domains with self-signed certificates, add the Base64 encoded file content here.
    # tls.crt: <base64 encoded server cert>
    # tls.key: <base64 encoded server key>

# Don't install Traefik by default.  Set to true to add it in.  Omitting it defaults to true, so beware.
traefik:
  install: false
  # experimental:
  #   plugins:
  #     enabled: true
  # additionalArguments:
  #   - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
  #   - "--experimental.plugins.htransformation.version=v0.2.7"
  # tlsStore:
  #   default:
  #     defaultCertificate:
  #       # See default-certificate secret(s) above
  #       secretName: default-certificate
  # tlsOptions:
  #   traefik-client-cert-option:
  #     clientAuth:
  #       clientAuthType: VerifyClientCertIfGiven
  #       secretNames:
  #         - cacert-secret
  # websecure:
  #   middlewares: 
  #     - default-traefik-passtlsclientcert@kubernetescrd
  #     - default-traefik-header-transform@kubernetescrd
  #   tls:
  #     options:
  #       - default-traefik-client-cert-option@kubernetescrd
