# Ensure the X-Forwarded-Tls-Client-Cert header is being set.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-passtlsclientcert
spec:
  passTLSClientCert:
    pem: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-header-transform
spec:
  plugin:
    htransformation:
      Rules:
        - Header: X-Forwarded-Tls-Client-Cert
          Name: Client certificate header rename
          Type: Rename
          Value: X-Client-Certificate

