bases:
- ../../../base/skaha
namespace: skaha-system
patchesStrategicMerge:
- skaha-tomcat-deployment.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: start-desktop
  files:
  - config/start-desktop.sh
  - config/build-menu.sh
- name: skaha-config
  behavior: merge
  files:
  - config/catalina.properties
  - config/k8s-resources.properties
  - config/skaha-software.properties
  - config/launch-carta.yaml
  - config/launch-notebook.yaml
  - config/launch-novnc.yaml
  - config/launch-headless.yaml
  - config/launch-software.yaml
  - config/service-notebook.yaml
  - config/ingress-notebook.yaml
  - config/service-desktop.yaml
  - config/ingress-desktop.yaml
  - config/service-carta.yaml
  - config/ingress-carta.yaml
generatorOptions:
 disableNameSuffixHash: true
