apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cavern-ingress
  namespace: {{ .Values.skaha.namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - host: {{ .Values.deployment.hostname }}
    http:
      paths:
      - path: {{ .Values.deployment.cavern.endpoint | default "/cavern" }}
        pathType: Prefix
        backend:
          service:
            name: cavern-tomcat-svc
            port:
              number: 8080
