apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cavern-tomcat
  name: cavern-tomcat
  namespace: {{ .Values.skaha.namespace }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      run: cavern-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cavern-tomcat
    spec:
      # The keys are enabled by default in the main values.yaml file.
      {{- with .Values.deployment.cavern.keys }}
      initContainers:
      - name: init-keys
        image: alpine:latest
        command: ['sh', '-c', 'apk --no-cache add openssh-keygen && ssh-keygen -b 2048 -t rsa -m pkcs8 -f ${TMP_KEY} -q -N "" && ssh-keygen -e -m pkcs8 -f ${TMP_KEY}.pub > /keys/{{ .public }} -q -N "" && mv ${TMP_KEY} /keys/{{ .private }}']
        env:
          - name: TMP_KEY
            value: temp-{{ $.Release.Name }}
        volumeMounts:
        - mountPath: "/keys"
          name: keys-volume
      {{- end }}
      containers:
      - image: {{ .Values.deployment.cavern.image }}
        imagePullPolicy: {{ .Values.deployment.cavern.imagePullPolicy }}
        name: cavern-tomcat
        resources:
          requests:
            memory: {{ .Values.deployment.cavern.resources.requests.memory }}
            cpu: {{ .Values.deployment.cavern.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.cavern.resources.limits.memory }}
            cpu: {{ .Values.deployment.cavern.resources.limits.cpu }}
        {{- with .Values.deployment.cavern.extraEnv }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        {{- with .Values.deployment.cavern.extraPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: "/config"
          name: config-volume
        {{- with .Values.deployment.cavern.keys }}
        - mountPath: "/config/{{ .subDir }}"
          name: keys-volume
        {{- end }}
        - mountPath: "{{ .Values.deployment.cavern.filesystem.dataDir }}"
          name: cavern-volume
        {{- with .Values.deployment.cavern.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: keys-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: cavern-config
      - name: cavern-volume
        {{- toYaml .Values.storage.service.spec | nindent 8 }}
      {{- with .Values.deployment.cavern.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
