apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cavern-tomcat
  name: cavern-tomcat
  namespace: {{ .Values.skaha.namespace }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      run: cavern-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cavern-tomcat
    spec:
      securityContext:
        fsGroup: {{ .Values.deployment.cavern.filesystem.rootOwner.gid }}
      initContainers:
      - name: init-cavern-fs
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'mkdir -p {{ .Values.deployment.cavern.filesystem.dataDir }}/cavern/home && mkdir -p {{ .Values.deployment.cavern.filesystem.dataDir }}/cavern/projects && chown {{ .Values.deployment.cavern.filesystem.rootOwner.uid }}:{{ .Values.deployment.cavern.filesystem.rootOwner.gid }} {{ .Values.deployment.cavern.filesystem.dataDir }}/cavern/home && chown {{ .Values.deployment.cavern.filesystem.rootOwner.uid }}:{{ .Values.deployment.cavern.filesystem.rootOwner.gid }} {{ .Values.deployment.cavern.filesystem.dataDir }}/cavern/projects']
        volumeMounts:
        - mountPath: "{{ .Values.deployment.cavern.filesystem.dataDir }}"
          name: cavern-volume
      containers:
      - image: {{ .Values.deployment.cavern.image }}
        imagePullPolicy: {{ .Values.deployment.cavern.imagePullPolicy }}
        name: cavern-tomcat
        resources:
          requests:
            memory: {{ .Values.deployment.cavern.resources.requests.memory }}
            cpu: {{ .Values.deployment.cavern.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.cavern.resources.limits.memory }}
            cpu: {{ .Values.deployment.cavern.resources.limits.cpu }}
        {{- with .Values.deployment.cavern.extraEnv }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        {{- with .Values.deployment.cavern.extraPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: "/config"
          name: config-volume
        - mountPath: "{{ .Values.deployment.cavern.filesystem.dataDir }}"
          name: cavern-volume
        {{- with .Values.deployment.cavern.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: cavern-config
      - name: cavern-volume
        {{- toYaml .Values.storage.service.spec | nindent 8 }}
      {{- with .Values.deployment.cavern.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
