apiVersion: apps/v1
kind: Deployment
metadata:
  name: cavern-uws-postgres
  namespace: {{ .Values.skaha.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cavern-uws-postgres
  template:
    metadata:
      labels:
        app: cavern-uws-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: cavern-uws-postgres-config
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresinit
            {{- if .Values.deployment.cavern.uws.db.storage }}
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            {{- end }}
      volumes:
        {{- if .Values.deployment.cavern.uws.db.storage }}
        - name: postgresdb
          {{- toYaml .Values.deployment.cavern.uws.db.storage.spec | nindent 10 }}
        {{- end }}
        - name: postgresinit
          configMap:
            name: cavern-uws-postgres-init
