bases:
- ../../../base/skaha
namespace: skaha-system
patchesStrategicMerge:
- skaha-tomcat-deployment.yaml
- carta-ingress.yaml
- desktop-ingress.yaml
- notebook-ingress.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: skaha-config
  behavior: merge
  files:
  - config/catalina.properties
  - config/k8s-resources.properties
  - config/skaha-software.properties
- name: skaha-wsproxy-config
  behavior: merge
  files:
  - config/k8s-config
generatorOptions:
 disableNameSuffixHash: true
