bases:
- ../../../base/skaha
namespace: skaha-system
patchesStrategicMerge:
- skaha-tomcat-deployment.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: skaha-config
  behavior: merge
  files:
  - config/catalina.properties
  - config/k8s-resources.properties
  - config/skaha-software.properties
  - config/launch-carta.yaml
  - config/launch-notebook.yaml
  - config/launch-novnc.yaml
  - config/launch-software.yaml
  - config/service-notebook.yaml
  - config/ingress-notebook.yaml
generatorOptions:
 disableNameSuffixHash: true
