
externalURL: https://images-rc.canfar.net

harborAdminPassword: changeme


#***************************************************
service:
  type: ClusterIP
  tls:
    enabled: true
    existingSecret: "canfar-net-cert-secret"



#***************************************************
ingress:
  enabled: true

  hosts:
    core: images-rc.canfar.net
    notary: notary-rc.canfar.net
  
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: null
    nginx.ingress.kubernetes.io/proxy-body-size: null



#***************************************************
persistence:
  enabled: true

  persistentVolumeClaim:

    registry:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-registry"
      accessMode: ReadWriteOnce
      size: 800Gi

    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-jobservice"
      accessMode: ReadWriteOnce
      size: 10Gi

    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: "harbor-chartmuseum"
      accessMode: ReadWriteOnce
      size: 40Gi

    trivy:
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 40Gi

  imageChartStorage:
    disableredirect: true


#***************************************************
core:
  priorityClassName: uber-user-preempt-high



#***************************************************
postgresql:
  enabled: true

  persistence:
    enabled: true
    storageClass: ""
    subPath: harbor-postgresql


#***************************************************
redis:
  enabled: true

  master:
    persistence:
      enabled: true
      storageClass: ""
      subPath: harbor-redis

    priorityClassName: uber-user-preempt-high

  slave:
    persistence:
      enabled: true
      storageClass: ""
      subPath: harbor-redis

