bases:
- ../../../base/arc
namespace: skaha-system
patchesStrategicMerge:
- arc-tomcat-deployment.yaml
- arc-sshd-deployment.yaml
- arc-ingress.yaml
- arc-sshd-ingress.yaml
configMapGenerator:
- name: arc-config
  behavior: merge
  files:
  - config/catalina.properties
  - config/Cavern.properties
generatorOptions:
 disableNameSuffixHash: true
