apiVersion: traefik.io/v1
kind: Middleware
metadata:
  name: skaha-carta-http-middleware-${skaha.sessionid}
spec:
  replacePathRegex:
    regex: ^/session/carta/http/${skaha.sessionid}(/|$)(.*)
    replacement: /$2

---
apiVersion: traefik.io/v1
kind: Middleware
metadata:
  name: skaha-carta-ws-middleware-${skaha.sessionid}
spec:
  replacePathRegex:
    regex: ^/session/carta/ws/${skaha.sessionid}(/|$)(.*)
    replacement: /$2

---
apiVersion: traefik.io/v1
kind: IngressRoute
metadata:
  name: skaha-carta-ingress-${skaha.sessionid}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`rc-uv.canfar.net`) && PathPrefix(`/session/carta/http/${skaha.sessionid}`)
    services:
    - kind: Service
      name: skaha-carta-svc-${skaha.sessionid}
      port: 6901
      scheme: http
    middlewares:
      - name: skaha-carta-http-middleware-${skaha.sessionid}
  - kind: Rule
    match: Host(`rc-uv.canfar.net`) && PathPrefix(`/session/carta/ws/${skaha.sessionid}`)
    services:
    - kind: Service
      name: skaha-carta-svc-${skaha.sessionid}
      port: 5901
      scheme: http
    middlewares:
      - name: skaha-carta-ws-middleware-${skaha.sessionid}
