namespace: skaha-workload
configMapGenerator:
- name: start-desktop-software
  files:
  - config/start-desktop-software.sh
  - config/build-astrosoftware-menu.sh
generatorOptions:
 disableNameSuffixHash: true
