# This is a sample PersistentVolume that is expected to be present.  It can be anything, so long as it can be bound by a PersistentVolumeClaim
# when Skaha is installed.  This is done by matching th labels.  The intent is that a Cluster Administrator will have a PersistentVolume setup,
# and will direct deployers on what label to use to bind to it.
# This will be used by the User Sessions when starting up to gain access to the shared Storage with the Skaha service.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: science-platform-volume  # Name is irrelevant
  labels:
    storage: local-storage # Labels are VERY relevant.  They should match the values.yaml configuration.
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/skaha-workload
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop  # Single node docker-desktop for macOS and Windows.
