apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "base.fullname" . }}-canfarops-general-harbor-binding
  labels:
  {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: general-user-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: canfarops
  namespace: '{{ .Release.Namespace }}'