apiVersion: v1
kind: ServiceAccount
metadata:
  name: sss
  namespace: {{ .Values.sssd.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skaha
  namespace: {{ .Values.skaha.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{ .Values.nfsServer.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nfsServer.replicas }}
  selector:
    matchLabels:
      role: nfs-server
    {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: nfs-server
      {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nfsServer.nfsServer.image.repository }}:{{ .Values.nfsServer.nfsServer.image.tag | default .Chart.AppVersion }}
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: mountd
        - containerPort: 111
          name: rpcbind
        resources: {{- toYaml .Values.nfsServer.nfsServer.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.nfsServer.nfsServer.containerSecurityContext
          | nindent 10 }}