apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prepare-cluster.fullname" . }}-ingresslog-role
  labels:
  {{- include "prepare-cluster.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get