apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: {{ .Values.nfsServer.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nfsServer.type }}
  selector:
    role: nfs-server
  {{- include "base.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nfsServer.ports | toYaml | nindent 2 -}}