apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{ .Values.skaha.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nfsServer.replicas }}
  selector:
    matchLabels:
      role: nfs-server
    {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: nfs-server
      {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nfs-server
        env:
          - name: KUBERNETES_CLUSTER_DOMAIN
            value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nfsServer.nfsServer.image.repository }}:{{ .Values.nfsServer.nfsServer.image.tag | default "latest" }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        resources: {{- toYaml .Values.nfsServer.nfsServer.resources | nindent 12 }}
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: {{ .Values.skaha.namespace }}
  labels:
  {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nfsServer.type }}
  selector:
    role: nfs-server  # Needs to match the deployment labels above.
  {{- include "base.selectorLabels" . | nindent 4 }}
  ports:
{{ .Values.nfsServer.nfsServer.ports | toYaml | nindent 2 }}

# Volume and claim for Skaha
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.skaha.namespace }}-cavern-pv
  namespace: {{ .Values.skaha.namespace }}
  labels:
    app: nfs-data
spec:
  claimRef:
    namespace: {{ .Values.skaha.namespace }}
    name: {{ .Values.skaha.namespace }}-cavern-pvc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs: 
    # URL for the NFS server
    # Can be accessed at the nfs-server.<nfs-namespace>.svc.cluster.local hostname.
    server: "nfs-service.{{ .Values.skaha.namespace }}.svc.cluster.local"
    path: "/"  # Refers to root of /exports folder on the NFS server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.skaha.namespace }}-cavern-pvc
  namespace: {{ .Values.skaha.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: nfs-data

---
# Volume and claim for Jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pv
  namespace: {{ index .Values "skaha-workload" "namespace" }}
  labels:
    app: workload-nfs-data
spec:
  claimRef:
    namespace: {{ index .Values "skaha-workload" "namespace" }}
    name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pvc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs: 
    # URL for the NFS server
    # Can be accessed at the nfs-server.<nfs-namespace>.svc.cluster.local hostname.
    server: "nfs-service.{{ .Values.skaha.namespace }}.svc.cluster.local"
    path: "/"  # Refers to root of /exports folder on the NFS server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pvc
  namespace: {{ index .Values "skaha-workload" "namespace" }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: workload-nfs-data
