apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prepare-cluster.fullname" . }}-nvidia-device-plugin-role
  labels:
  {{- include "prepare-cluster.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use