# Volume and claim for Skaha
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.skaha.namespace }}-cavern-pv
  labels:
    app: storage-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/skaha
  nodeAffinity:
{{ toYaml .Values.volumes.nodeAffinity | nindent 4 }}
---
# Volume and claim for Jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pv
  labels:
    app: workload-storage-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/skaha-workload
  nodeAffinity:
{{ toYaml .Values.volumes.nodeAffinity | nindent 4 }}
# Volume for Harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.skaha.namespace }}-harbor-pv
  labels:
    app: harbor-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/skaha-storage
  nodeAffinity:
{{ toYaml .Values.volumes.nodeAffinity | nindent 4 }}
