apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "skaha-workload" "namespace" }}-cavern-pvc
  namespace: {{ index .Values "skaha-workload" "namespace" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: workload-storage-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.skaha.namespace }}-cavern-pvc
  namespace: {{ .Values.skaha.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: storage-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.skaha.namespace }}-harbor-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: harbor-data
