# This is a sample PersistentVolume that is expected to be present.  It can be anything, so long as it can be bound by a PersistentVolumeClaim
# when Skaha is installed.  This is done by matching th labels.  The intent is that a Cluster Administrator will have a PersistentVolume setup,
# and will direct deployers on what label to use to bind to it.
# This will be used by the User Sessions when starting up to gain access to the shared Storage with the Skaha service.
# This default will create a hostPath volume with no declared PV.
#
{{- if .Values.storage.service.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Values.storage.service.claimName }}
  namespace: {{ .Values.skaha.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
{{- toYaml .Values.storage.service.labels | nindent 6 }}
{{ end }}
