apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prepare-cluster.fullname" . }}-servops-secrets-skaha-system-binding
  labels:
  {{- include "prepare-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "prepare-cluster.fullname" . }}-secrets-clusterrole'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: servops
  namespace: '{{ .Release.Namespace }}'