apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prepare-cluster.fullname" . }}-skaha-restricted-sssd-workload-binding
  labels:
  {{- include "prepare-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-sssd-clusterrole
subjects:
- kind: ServiceAccount
  name: '{{ include "prepare-cluster.fullname" . }}-skaha'
  namespace: '{{ .Release.Namespace }}'
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'