apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "base.fullname" . }}-skaha-jobs-system-binding
  labels:
  {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "base.fullname" . }}-jobs-clusterrole'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: canfarops
  namespace: '{{ .Release.Namespace }}'
- kind: ServiceAccount
  name: '{{ include "base.fullname" . }}-skaha'
  namespace: '{{ .Release.Namespace }}'