apiVersion: v1
kind: Service
metadata:
  name: cavern-sshd-svc
  labels:
    run: cavern-sshd-svc
spec:
  ports:
  - port: 22
    protocol: TCP
    name: cavern-ssh-port
  selector:
    run: cavern-sshd
