kubernetesClusterDomain: cluster.local

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# It's best to keep these set as such, unless you're willing to change these in several places.
skaha:
  namespace: skaha-system

# Skaha web service deployment
deployment:
  hostname: example.org  # Change this!
  cavern:
    image: images.opencadc.org/platform/cavern:0.5.7
    imagePullPolicy: Always

    # How cavern identifies itself.
    resourceID: "ivo://example.org/cavern"

    # The Resource ID of the Service that contains the Posix Mapping information
    posixMapperResourceID: "ivo://opencadc.org/posix-mapper"

    # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
    oidcURI: https://ska-iam.stfc.ac.uk/

    # ID (URI) of the GMS Service.
    gmsID: ivo://skao.int/gms

    # The endpoint to serve this from.  Defaults to /cavern.
    # endpoint: "/cavern"

    # filesystem:
      # persistent data directory in container
      # dataDir: "/data"

      # (Optional) relative path to the node/file content that could be mounted in other containers.
      # subPath: "/cavern"

      # The adminUsername is required to be set whomever has admin access over the
      # filesystem.dataDir above.
      # rootOwner:
        # adminUsername: "root"
        # username: "root"
        # uid: 1000
        # gid: 1000

    # Public/private key pair to generate pre-auth URLs to cavern.  This is required to enable the User Storage UI's non-public downloads, but optional
    # if not running the Storage UI.
    # 
    # By default, an initContainer will generate keys with the given name, in the given sub directory.  For an easy setup system, these can be left alone safely.
    #
    # Deployers can override these files if they want to inject them separately.
    # See https://github.com/opencadc/core/tree/master/cadc-keygen for instructions on creating the key pair.
    keys:
      private: cavern-private.key
      public: cavern-public.key

      # Keys will be available in the "keys" folder in the default config folder.
      subDir: keys


      # (optional) base directory exposed for sshfs mounts
      # sshfs:
      #   serverBase: {server}[:{port}]:{path}

    # The IdentityManager class handling authentication.  This should generally be left alone
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # When using a database to connect to UWS.
    uws:
      db:
        username: uwsuser
        password: uwspwd
        database: uws
        schema: uws
        maxActive: 2
        # storage:
        #   spec:
        #     hostPath:
        #       path: "/cavern-uws/data"

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: skaha-cacert-secret

    # Resources provided to the Skaha service.
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # cavern-cacert-secret:
  #   ca.crt: <base64 encoded CA crt>

# Exposed extra ports.  Uncomment the java-debug port to expose and debug issues.
# service:
#   cavern:
#     extraPorts:
  #   - port: 5555
  #     protocol: TCP
  #     name: java-debug

# Set these appropriately to match your Persistent Volume Claim labels.
storage:
  service:
    spec:
      # YAML for service mounted storage.
      # Example is the persistentVolumeClaim below.  Do not uncomment this
      # or Helm will use it as the default, even if a different spec
      # is specified.
      # persistentVolumeClaim:
      #   claimName: skaha-pvc